export const REQUEST_ADD_TODO = "REQUEST_ADD_TODO";
export const SUCCESS_ADD_TODO = "SUCCESS_ADD_TODO";
export const FAIL_ADD_TODO = "FAIL_ADD_TODO";

export const REQUEST_DELETE_TODO = "REQUEST_DELETE_TODO";
export const SUCCESS_DELETE_TODO = "SUCCESS_DELETE_TODO";
export const FAIL_DELETE_TODO = "FAIL_DELETE_TODO";

export const REQUEST_FETCH_TODO = "REQUEST_FETCH_TODO";
export const SUCCESS_FETCH_TODO = "SUCCESS_FETCH_TODO";
export const FAIL_FETCH_TODO = "FAIL_FETCH_TODO";

export const REQUEST_UPDATE_STATUS_TODO = "REQUEST_UPDATE_STATUS_TODO";
export const SUCCESS_UPDATE_STATUS_TODO = "SUCCESS_UPDATE_STATUS_TODO";
export const FAIL_UPDATE_STATUS_TODO = "FAIL_UPDATE_STATUS_TODO";

export const REQUEST_UPDATE_NAME_TODO = "REQUEST_UPDATE_NAME_TODO";
export const SUCCESS_UPDATE_NAME_TODO = "SUCCESS_UPDATE_NAME_TODO";
export const FAIL_UPDATE_NAME_TODO = "FAIL_UPDATE_NAME_TODO";
